import axios from "axios";

const getBaseURL = () => {
    // 1. If explicit env variable is set during build or runtime
    if (import.meta.env.VITE_API_URL) {
        return import.meta.env.VITE_API_URL;
    }
    // 2. In production browser environment (not localhost), use relative path /api
    if (typeof window !== "undefined" && !window.location.hostname.includes("localhost") && !window.location.hostname.includes("127.0.0.1")) {
        return "/api";
    }
    // 3. Local development default
    return "http://localhost:5000/api";
};

const api = axios.create({
    baseURL: getBaseURL(),
});

export const getSelectedAgent = () => {
    return localStorage.getItem("toolzz_selected_agent") || "auto";
};

export const setSelectedAgent = (agentId) => {
    localStorage.setItem("toolzz_selected_agent", agentId);
    window.dispatchEvent(new Event("toolzz_agent_changed"));
};

export const fetchAIProviders = async () => {
    try {
        const response = await api.get("/ai/providers");
        return response.data?.data || response.data || [];
    } catch (err) {
        console.warn("Failed to fetch AI providers from backend:", err.message);
        return [];
    }
};

export const generateAI = async (tool, input, providerOverride) => {
    const provider = providerOverride || getSelectedAgent();
    const response = await api.post("/ai", {
        tool,
        input,
        provider,
    });
    
    const result = response.data?.data?.result || response.data?.result;
    if (!result) {
        throw new Error(response.data?.message || "No response generated by AI server.");
    }
    return result;
};

export default api;